Use veevasystems;
CREATE TABLE Salesman_Jocata (
    salesman_id INT PRIMARY KEY,
    name VARCHAR(50),
    city VARCHAR(50),
    commission DECIMAL(4,2)
);
INSERT INTO Salesman_Jocata (salesman_id, name, city, commission)
VALUES
(5001, 'James Hoog', 'New York', 0.15),
(5002, 'Nail Knite', 'Paris', 0.13),
(5005, 'Pit Alex', 'London', 0.11),
(5006, 'Mc Lyon', 'Paris', 0.14),
(5003, 'Lauson Hen', 'San Jose', 0.12),
(5007, 'Paul Adam', 'Rome', 0.13);

CREATE TABLE Orders_Jocata (
    ord_no INT PRIMARY KEY,
    purch_amt DECIMAL(10,2),
    ord_date DATE,
    customer_id INT,
    salesman_id INT,
    FOREIGN KEY (salesman_id) REFERENCES Salesman_Jocata(salesman_id)
);

INSERT INTO Orders_Jocata (ord_no, purch_amt, ord_date, customer_id, salesman_id)
VALUES
(70001, 150.50, '2012-10-05', 3005, 5002),
(70009, 270.65, '2012-09-10', 3001, 5005),
(70002, 65.26, '2012-10-05', 3002, 5001),
(70004, 110.50, '2012-08-17', 3009, 5003),
(70007, 948.50, '2012-09-10', 3005, 5002),
(70005, 2400.60, '2012-07-27', 3007, 5001),
(70008, 5760.00, '2012-09-10', 3002, 5001),
(70010, 1983.43, '2012-10-10', 3004, 5006),
(70003, 2480.40, '2012-10-10', 3009, 5003),
(70012, 250.45, '2012-06-27', 3008, 5002),
(70011, 75.29, '2012-08-17', 3003, 5007),
(70013, 3045.60, '2012-04-25', 3002, 5001);

/*1.From the above tables write a sql query to find all the orders issued by salesman paul adam*/
Select *
from orders_jocata o 
join salesman_jocata s
on o.salesman_id=s.salesman_id
where s.name='Paul Adam';

/*2.Write SQL Query to find all the orders generated by London based sales people*/
Select *
from orders_jocata o 
join salesman_jocata s
on o.salesman_id=s.salesman_id
where s.city='London';

/*3.Write an SQL Query to find all the orders generated by sales people who works for customer id 3007*/
Select *
from orders_jocata o 
join salesman_jocata s
on o.salesman_id=s.salesman_id
where o.customer_id=3007;

/*4.Display all the orders exceeding average value on 10th October 2012*/
select * from orders_jocata
where purch_amt>
(select avg(purch_amt) 
from orders_jocata
where ord_date='2012-10-10');

/*5.Display all the orders generated in new York city*/
Select *
from orders_jocata o 
join salesman_jocata s
on o.salesman_id=s.salesman_id
where s.city='New York';